server:
  port: 8080
  # 开启浏览器压缩
  compression:
    enabled: true
endpoints:
  enabled: true
  actuator:
    sensitive: false
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: root!@#
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update

#mybatis:
#  config-location: /mybatis/mybatis-config.xml
